### ISSUE TITLE
Scanner model unknown

### ISSUE THREAD

**Issue by TheLinuxMafia** [shaxxx/sunmi_barcode_plugin#1]
When i call page with your example, i get "Scanner model: Unknown", an in Debug Console i got this error: No implementation found for method getScannerModel on channel hr.integrator.flutter_sunmi_barcode_scanner

Do you think it's unsupported scanner ?
Please let me know.
Best Regards.

**Comment by shaxxx** [comment]
What model are you using? This plugin implements SDK for Sunmi HARDWARE scanner, you do have one do you?
It's hard to tell, it's a bit odd that you get "No implementation found" error.
You can't do much without logcat, open it in Android Studio and run example app to see the logs.
Do you get "Connected to Sunmi scanner service" or do you get "Failed to connect to Sunmi scanner service"
When you use barcode scanner to scan do you see any system intents fired up? You should get some kind of global system event.

Can you make complete unfiltered log with logcat (not just example app) and put it on pastebin?

- turn on the logcat in Android studio
- clear all filters in logcat so you see all the events  (make sure you're logging everyting not only currently active app)
- clear logcat log before continuing, so we have fresh start
- make a scan with hardware scanner (this should fire some events visible in logcat)
- open example app and wait to see No implementation found in debug console
- wait few seconds, save the logcat log, put it on pastebin 

Or simply use [my other plugin](https://pub.dev/packages/flutter_barcode_listener) that should work with all hardware scanners.

**Comment by shaxxx** [comment]
Any news?

**Comment by Srini-B** [comment]
@shaxxx Just wanted to ask will this support V2 device 
https://www.sunmi.com/en/V2/

**Comment by shaxxx** [comment]
Plugin supports Sunmi Print service on Android devices. If V2 uses same Android service it's already supported.
I don't have V2 device to test it.
